# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com.booking: debug

